version: '3'

services:
  app:
    build:
      context: .
      target: production
    image: nextjs-app:latest
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://postgres:example@db:5432/dev-db"
    depends_on:
      - db
    volumes:
      - .:/app
    # Restart policy ensures that Docker attempts to restart the container if it crashes.
    restart: always
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dev-db
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always

volumes:
  pg-data:
